apiVersion: v1
kind: Service
metadata:
  name: akuudagram-backend
  labels:
    app: akuudagram-backend
spec:
  selector:
    app: akuudagram-backend
  ports:
  - name: "backend-feed"
    port: 8081
    targetPort: 8081
  - name: "backend-users"
    port: 8082
    targetPort: 8082
